name: recare
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py311h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py311h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.0.30=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py311h06a4308_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311hac6e08b_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - pytorch=2.1.0=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - setuptools=72.1.0=py311h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=py311h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.1.0=py311_cu121
  - torchtriton=2.1.0=py311
  - torchvision=0.16.0=py311_cu121
  - tornado=6.4.2=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=py311h06a4308_0
  - urllib3=2.3.0=py311h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - click==8.1.8
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.12.1
      - docker-pycreds==0.4.0
      - einops==0.3.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - hf-xet==1.1.0
      - huggingface-hub==0.25.2
      - humanfriendly==10.0
      - imageio==2.37.0
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - kornia==0.6.0
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - markdown==3.8
      - matplotlib==3.10.3
      - multidict==6.4.3
      - narwhals==1.40.0
      - nudenet==3.4.2
      - nudenetclassifier==2.1.1
      - numba==0.61.2
      - numpy==1.24.4
      - omegaconf==2.1.1
      - onnxruntime==1.21.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - pandas==2.2.3
      - plotly==6.1.0
      - progressbar2==4.5.0
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydeprecate==0.3.1
      - pydload==1.0.9
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - python-utils==3.9.1
      - pytorch-lightning==1.4.2
      - pytz==2025.2
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - segment-anything==1.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - soupsieve==2.7
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - tokenizers==0.13.3
      - torchmetrics==0.6.0 
      - tqdm==4.67.1
      - transformers==4.25.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - umap-learn==0.5.7
      - uuid==1.30
      - wandb==0.19.10
      - werkzeug==3.1.3
      - yarl==1.20.0
